/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.parser;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Properties;

/**
 *
 * @author ahmed.elemam
 */
public class ISO_parer extends javax.swing.JFrame {

    
    
    /**
     * Creates new form ISO_parer
     * 0 binary
     * 1 char
     * 2 number
     * 3 alphanumeric characters
     * 4 field containing magnetic track data
     * 5 LL one byte
     * 6 LLL two byte
	 
	 
	 another number 
	 0 Fixed
	 1 .. up to
	 3 dynmaic with lenght byte
     */
    public ISO_parer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bank Miser Parser");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("Msg");

        jButton1.setText("Parse");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        Properties prop = new Properties();
	InputStream input = null;

	try {

		input = new FileInputStream("src\\com\\parser\\Iso.properties");

		// load a properties file
		prop.load(input);
                String field1_name =prop.getProperty("field1_name");
                String field1_number =prop.getProperty("field1_number");
                String field1_length =prop.getProperty("field1_length");
                String field1_type =prop.getProperty("field1_type");
                
                
                String text ="01 D1 49 53 4F 30 34 36 35 32 31 31 31 30 35 30 30 30 31 32 30 30 F2 34 87 41 60 E1 8A 03 00 00 00 00 00 00 00 00 16 34 32 30 35 38 35 31 31 39 30 30 30 38 38 35 35 30 30 30 30 30 30 30 30 30 30 30 30 30 38 30 30 30 30 30 30 30 30 37 39 31 38 30 37 31 35 31 32 34 37 34 30 31 36 30 39 30 37 31 35 38 31 30 31 30 31 35 31 30 31 34 63 30 30 30 32 30 30 34 38 31 34 06 30 31 31 32 30 30 08 30 30 30 30 30 30 30 30 32 34 32 30 35 38 35 31 31 39 30 30 30 38 38 35 35 44 31 36 30 39 32 32 36 31 30 30 30 30 36 39 38 36 32 33 30 31 37 36 34 30 30 34 37 34 30 30 30 31 30 30 35 20 20 20 46 20 20 45 44 43 20 44 45 4D 4F 20 41 50 50 4C 49 43 41 54 49 4F 4E 20 20 20 53 50 45 43 54 52 41 20 54 45 43 48 4E 4F 4C 4F 47 49 45 53 20 30 30 33 38 50 31 30 30 33 32 41 35 35 34 41 39 36 34 35 39 45 33 36 38 42 46 36 30 42 39 32 37 45 39 46 34 41 44 31 34 45 39 38 31 38 09 30 31 30 31 30 30 30 30 30 01 35 5F 2A 02 08 40 5F 34 01 00 82 02 7C 00 84 07 A0 00 00 00 03 10 10 95 05 08 40 00 80 00 9A 03 18 07 15 9C 01 00 9F 02 06 00 00 00 08 00 00 9F 03 06 00 00 00 00 00 00 9F 09 02 00 8C 9F 10 07 06 01 0A 03 A4 A8 04 9F 1A 02 08 40 9F 1E 08 32 4B 36 32 34 34 37 37 9F 26 08 FE 77 DA BF 9A 91 9B F2 9F 27 01 80 9F 33 03 E0 F0 C8 9F 34 03 41 03 02 9F 35 01 22 9F 36 02 04 31 9F 37 04 E3 2C CD 03 9F 41 03 00 00 79 00 25 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 00 00 00 00 00 00 00 00";
                        
                        //jTextArea1.getText();
                
                 String [] data =text.split(" ");
                
                String[] f_name=field1_name.split(",");
                String[] f_number=field1_number.split(",");
                String[] f_length=field1_length.split(",");
                String[] f_type=field1_type.split(",");
                
     String [] header = new String[18];
         	
for(int i=0;i<18;i++){
    header[i]=data[i];     
}     
            System.out.println("header "+Arrays.toString(header));
            
            
               String [] msgid = new String[4];
 int j=0;             
for(int i=18;i<22;i++){
    msgid[j]=data[i]; 
    j++;    
}   

 System.out.println("msgid "+Arrays.toString(msgid));

               String [] Map = new String[8];
               String [] B_Map = new String[8];
  j=0;             
for(int i=22;i<22+8;i++){
    Map[j]=String.format("%08d", Integer.parseInt(hexToBin(data[i])) ); 
    B_Map[j]=data[i]; 
    j++;    
}   
 System.out.println("B_Map "+Arrays.toString(Map));
 System.out.println("Map "+Arrays.toString(B_Map));

 
// get the property value and print it out
                
 System.out.println(f_name.length+" "+f_number.length+" "+f_length.length+" "+f_type.length+" ");
 
 int loop_text=22+8;
 int field_num=1;

  System.out.println("Map "+Arrays.toString(f_number));
 
for(int i=0;i<f_number.length;i++){
   
    field_num=Integer.parseInt(f_number[i]);
    
    System.out.println("calcu "+field_num+" "+String.valueOf(((int)field_num/8)) +" "+String.valueOf((field_num%8)!=0? field_num-(((int)field_num/8)*8)-1 : 0));
    
   
  
     if(Map[((int)field_num/8)].charAt(((field_num%8)!=0? field_num-(((int)field_num/8)*8)-1 : 0))=='1'){
        
        int length=0;
      
       StringBuilder value=new StringBuilder();
       j=0;
       
       if(f_type[i].charAt(1)=='0'){
             if(f_type[i].charAt(0)=='1' || f_type[i].charAt(0)=='2' || f_type[i].charAt(0)=='3' || f_type[i].charAt(0)=='4'){
 
           length=Integer.parseInt(f_length[i]);
           System.out.println(f_type[i].charAt(0)+""+f_type[i].charAt(1)+" length "+length);
       
       }else if(f_type[i].charAt(0)=='0' ){     
           length=Integer.parseInt(f_length[i])/8;
           System.out.println(f_type[i].charAt(0)+""+f_type[i].charAt(1)+" length "+length);  
       }
           
     }else if(f_type[i].charAt(1)=='1'){
             if(f_type[i].charAt(0)=='1' || f_type[i].charAt(0)=='2' || f_type[i].charAt(0)=='3' || f_type[i].charAt(0)=='4'){
 
           length=Integer.parseInt(f_length[i]);
           System.out.println(f_type[i].charAt(0)+""+f_type[i].charAt(1)+" length "+length);
       
       }else if(f_type[i].charAt(0)=='0' ){     
           length=Integer.parseInt(f_length[i])/8;
           System.out.println(f_type[i].charAt(0)+""+f_type[i].charAt(1)+" length "+length);  
       }else  if(f_type[i].charAt(0)=='5'){
 
           length=Integer.parseInt(data[loop_text]);
           loop_text=loop_text+1;
           System.out.println("53 length "+length);
       
       }else if(f_type[i].charAt(0)=='6'){
            
                   StringBuilder len=new StringBuilder();
                   len.append(data[loop_text]);
                   len.append(data[loop_text+1]);
 
           length=Integer.parseInt(len.toString());
           loop_text=loop_text+2;
           System.out.println("63 length "+length);
       
       }
           
     }else if(f_type[i].charAt(1)=='3'){
           
       if(f_type[i].charAt(0)=='5'){
 
           length=Integer.parseInt(data[loop_text]);
           loop_text=loop_text+1;
           System.out.println("53 length "+length);
       
       }else if(f_type[i].charAt(0)=='6'){
            
                   StringBuilder len=new StringBuilder();
                   len.append(data[loop_text]);
                   len.append(data[loop_text+1]);
 
           length=Integer.parseInt(len.toString());
           loop_text=loop_text+2;
           System.out.println("63 length "+length);
       
       }
       }
       
 
        for(int c=loop_text;c<loop_text+length;c++){
        //    System.out.println("com.parser.ISO_parer.jButton1MouseClicked( ) "+c);
         value.append(data[c]);
          
         } 
        loop_text=loop_text+length;
        
          System.out.println(f_name[i]+" "+value.toString());
    }
    
    
   
    
    
    

   // System.out.println("Field "+f_number[i] +" "+f_name[i]+" "+f_length[i]+" "+f_type[i]);
}
                
                
	} catch (IOException ex) {
		ex.printStackTrace();
	} finally {
		if (input != null) {
			try {
				input.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ISO_parer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ISO_parer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ISO_parer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ISO_parer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISO_parer().setVisible(true);
            }
        });
    }
    
    
    static String hexToBin(String s) {
  return new BigInteger(s, 16).toString(2);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
